### PR TITLE
Hiera friendly

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@mcanevet How does this PR look? Would like to get feedback before I write the spec tests.

The purpose is to be able to specify a hash of the defined types in Hiera, so we can drive the infrastructure from that data instead of having to express the data in Puppet code or write glue code to poll Hiera.

Such as

```yaml
kmod::blacklists:
  'pcspkr':
    ensure: 'present'
  'foo':
    ensure: 'present'
  'bar':
    ensure: 'absent'
```

**Comment by mcanevet** [comment]
I'm not really found of putting explicit hiera lookups in a component module even if I see the point. I'l prefer have this kind of usage:

```puppet
class { '::kmod':
  aliases    => hiera_hash('kmod::aliases'),
  blacklists => hiera_hash('kmod::blacklists'),
}
```

And having just this in `Class[kmod]`:

```puppet
class kmod(
  $aliases = {},
  $blacklists = {},
) {
  create_resources(kmod::alias, $aliases)
  create_resources(kmod::blacklist, $blacklists)
}
```

@raphink what do you think?

ps: @ghoneycutt BTW about all the style changes, is there any "Style Guide" related to this?

**Comment by txaj** [comment]
:+1: I don't think the hiera lookups should be explicit in a module like this. Maybe in a wrapper but not the module itself

**Comment by ghoneycutt** [comment]
@raphink @mcanevet 

Thank you for reviewing this PR. I would agree that having to call hiera_hash() or hiera_array() is not pretty, though this pattern is needed so that you can specify if you want hiera to return the first match (normal behavior) or you want it to do a merge (hiera_hash() and hiera_array() do this).

Generally in the case of specifying data for defined types, you want to do a merge lookup, so they can be specified at different levels of the hierarchy. Puppet does not have a means for you to specify how this happens, which is why I've implemented this pattern.

In your suggestion, one would have to use the parameterized class syntax, which I do not use as it brings on containment issues. More importantly though, it requires more code to express what I want, which means that I cannot use this module without writing more code. The goal would be that I could use this module and drive it entirely with data from Hiera, including how to do the lookups in Hiera (normal or merged).

**Comment by ghoneycutt** [comment]
@mcanevet The style related changes are mostly not in the style guide. They are mostly white space and new line additions to make the code more consistent and easier to read. The exceptions being arrows not aligned in README. Resource arrangement in init.pp with the file resources. And while parameters to classes do not specifically fall under arrow alignment, this is a common practice, so I aligned those.

**Comment by mcanevet** [comment]
@ghoneycutt still not convinced by adding explicit hiera lookup at the component layer...
@raphink what do we do? close as WONTMERGE?

**Comment by ghoneycutt** [comment]
@mcanevet @raphink The issue is that while Puppet does have the ability to pass in data for parameters through the use of Hiera, it does not have the ability to inform Hiera as to how the lookup should happen (first match or merging of all matches). This code would empower the module to do so. Without this patch, we would need to maintain a separate module that parrots the parameters of this one or fork, both of which are not well suited for long term maintainability.

I would agree that having `hiera()` calls instead of using parameters is not a good pattern, nor is using `hiera()`, `hiera_array()` and `hiera_hash()` to call arbitrary keys instead of the `class::param` convention. This code does neither of those and simply allows the user to control how Hiera does the lookup.

**Comment by mcanevet** [comment]
@ghoneycutt your argument is valid for all modules actually...
@raphink and I still think that this complexity should go into a profile layer and do not want to merge this in this component level module.
Sorry, but I'll close this PR without merging, feel free to reopen if you have another argument.

**Comment by ghoneycutt** [comment]
@anders-larsson Suggest using the camptocamp code instead of my branch as theirs will be maintained and creating a wrapper module that does the hiera lookup bits by taking my code from 

https://github.com/ghoneycutt/puppet-kmod/commit/17a134260299c827f96386d94a5f7500d12a0389#commitcomment-14435419

**Comment by anders-larsson** [comment]
@ghoneycutt oh. I totally missed that there had been a pull request open for this. Thank you for your suggestion!

**Pull request closed without merging**
